from pydantic import BaseModel, Field
from typing import List

class ChatRequest(BaseModel):
    question: str = Field(..., description="The query or question for the RAG agent.")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The response answer generated by the RAG agent.")
    sources: List[str] = Field(default=[], description="The list of source document filenames used in retrieval context.")
